# Generated by Django 6.1.2 on 2026-10-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimPoliza',
            fields=[
                ('id_poliza', models.UUIDField(primary_key=True, serialize=False)),
                ('id_asegurado', models.UUIDField(blank=True, null=True)),
                ('product_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dim_poliza',
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_siniestro', models.UUIDField(unique=True)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'fraud_flags',
            },
        ),
        migrations.CreateModel(
            name='AvgResolutionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('period', models.DateField()),
                ('avg_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resolved_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'avg_resolution_time',
                'constraints': [models.UniqueConstraint(fields=('product_type', 'period'), name='uq_avg_resolution_time')],
            },
        ),
        migrations.CreateModel(
            name='ClaimsByType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('period', models.DateField()),
                ('claim_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'db_table': 'claims_by_type',
                'constraints': [models.UniqueConstraint(fields=('product_type', 'period'), name='uq_claims_by_type')],
            },
        ),
        migrations.CreateModel(
            name='DimSiniestro',
            fields=[
                ('id_siniestro', models.UUIDField(primary_key=True, serialize=False)),
                ('id_poliza', models.UUIDField(blank=True, null=True)),
                ('id_asegurado', models.UUIDField(blank=True, null=True)),
                ('product_type', models.CharField(max_length=20)),
                ('reported_at', models.DateTimeField()),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('resuelto', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dim_siniestro',
                'indexes': [models.Index(fields=['id_asegurado'], name='idx_dim_siniestro_asegurado')],
            },
        ),
        migrations.CreateModel(
            name='LossRatioByProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('period', models.DateField()),
                ('premiums_earned', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('claims_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('loss_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'loss_ratio_by_product',
                'constraints': [models.UniqueConstraint(fields=('product_type', 'period'), name='uq_loss_ratio_by_product')],
            },
        ),
    ]
